/* CRIAÇÃO DO BANCO DE DADOS */
CREATE DATABASE BDCADASTRO;

/* ABRIR O BANCO DE DADOS */
USE BDCADASTRO;

/* CRIAÇÃO DA TABELA PRODUTO */
CREATE TABLE PRODUTO (
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL
);
